'use strict';
const ExcelJS=require('exceljs'),F=require('../domain/factory.cjs');
const labels={ru:{summary:'Отчёт',daily:'По дням',lines:'Линии',stops:'Простои',period:'Период',date:'Дата',plan:'План сборки',actual:'Выпуск сборки',completion:'Выполнение плана',downtime:'Простой оборудования, мин',quality:'Доля годных',inspected:'Проверено',defective:'Брак',section:'Участок',line:'Линия',hours:'Работа, ч',load:'Загрузка',equipment:'Оборудование',reason:'Причина',metric:'Показатель',value:'Значение',current:'Текущая симуляция',time:'Время симуляции, сек',timely:'Заказы в срок',orders:'Всего заказов',station:'Станция',source:'Источник',missing:'Нет данных'},en:{summary:'Report',daily:'Daily',lines:'Lines',stops:'Downtime',period:'Period',date:'Date',plan:'Assembly plan',actual:'Assembly output',completion:'Plan completion',downtime:'Equipment downtime, min',quality:'Good units share',inspected:'Inspected',defective:'Scrap',section:'Section',line:'Line',hours:'Work hours',load:'Utilization',equipment:'Equipment',reason:'Reason',metric:'Metric',value:'Value',current:'Current simulation',time:'Simulation time, sec',timely:'Orders on time',orders:'Total orders',station:'Station',source:'Source',missing:'No data'},kk:{summary:'Есеп',daily:'Күндер бойынша',lines:'Желілер',stops:'Тоқтау',period:'Кезең',date:'Күні',plan:'Құрастыру жоспары',actual:'Құрастыру өнімі',completion:'Жоспар орындалуы',downtime:'Жабдық тоқтауы, мин',quality:'Жарамды өнім үлесі',inspected:'Тексерілген',defective:'Ақау',section:'Учаске',line:'Желі',hours:'Жұмыс, сағ',load:'Жүктеме',equipment:'Жабдық',reason:'Себеп',metric:'Көрсеткіш',value:'Мән',current:'Ағымдағы симуляция',time:'Симуляция уақыты, сек',timely:'Уақытындағы тапсырыс',orders:'Барлық тапсырыс',station:'Станция',source:'Дереккөз',missing:'Дерек жоқ'}};
function daily(dataset,from,to){const o=F.overview(dataset,from,to);const dates=[...new Set([...o.rows,...o.stops,...dataset.quality.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to))].map(r=>r.date))].sort();return {overview:o,days:dates.map(date=>({date,...F.overview(dataset,date,date)}))};}
async function workbook({dataset,from=null,to=null,language='ru',simulation=null}){
 const l=labels[language]||labels.ru,w=new ExcelJS.Workbook();w.creator='ALLUR demo version';
 const add=(name,headers,rows)=>{const s=w.addWorksheet(name);s.addRow(headers);rows.forEach(r=>s.addRow(r.map(x=>x===null?l.missing:x)));s.views=[{state:'frozen',ySplit:1}];s.autoFilter={from:{row:1,column:1},to:{row:s.rowCount,column:headers.length}};s.getRow(1).height=30;s.getRow(1).eachCell(c=>{c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFCC45'}};c.font={bold:true,color:{argb:'FF242424'}};});s.columns.forEach((c,i)=>{c.width=i===0?32:24;});s.eachRow((r,i)=>{r.alignment={vertical:'middle',wrapText:true};if(i>1)r.height=28;});return s;};
 const date=s=>new Date(s+'T00:00:00Z');
 if(simulation){const {snapshot:s,kpi}=simulation;const summary=add(l.summary,[l.metric,l.value],[[l.source,l.current],[l.time,s.t],[l.actual,kpi.produced],[l.completion,kpi.completion],[l.timely,kpi.timely],[l.orders,kpi.orders],[l.downtime,kpi.downtime/60],[l.defective,kpi.scrapped],[l.quality,kpi.quality]]);summary.getCell('B5').numFmt='0.0%';summary.getCell('B10').numFmt='0.0%';add(l.lines,[l.station,l.downtime],s.stations.map(x=>[x.i+1,(x.time.repair+x.time.materials+x.time.operator+x.time.blocked+x.time.starved)/60]));}
 else {const {overview:o,days}=daily(dataset,from,to);const summary=add(l.summary,[l.metric,l.value],[[l.source,dataset.source.name],[l.period,(from||'')+' — '+(to||'')],[l.plan,o.plan],[l.actual,o.completed],[l.completion,o.completion],[l.downtime,o.stops.reduce((n,r)=>n+r.minutes,0)],[l.inspected,o.quality?.inspected??null],[l.defective,o.quality?.defective??null],[l.quality,o.quality?1-o.quality.defectRate:null]]);summary.getCell('B6').numFmt='0.0%';summary.getCell('B10').numFmt='0.0%';
 const d=add(l.daily,[l.date,l.plan,l.actual,l.completion,l.downtime,l.inspected,l.defective],days.map(x=>[date(x.date),x.plan,x.completed,x.completion,x.stops.reduce((n,r)=>n+r.minutes,0),x.quality?.inspected??null,x.quality?.defective??null]));d.getColumn(1).numFmt='dd.mm.yyyy';d.getColumn(4).numFmt='0.0%';
 const lines=add(l.lines,[l.date,l.line,l.section,language==='ru'?'План':language==='kk'?'Жоспар':'Plan',language==='ru'?'Факт':language==='kk'?'Нақты':'Actual',l.hours,l.load],o.rows.map(r=>[date(r.date),r.line,r.section,r.plan,r.actual,r.workHours,r.loadPct/100]));lines.getColumn(1).numFmt='dd.mm.yyyy';lines.getColumn(7).numFmt='0.0%';
 const stops=add(l.stops,[l.date,l.section,l.equipment,l.reason,l.downtime],o.stops.map(r=>[date(r.date),r.section,r.equipment,r.reason,r.minutes]));stops.getColumn(1).numFmt='dd.mm.yyyy';}
 w.eachSheet(s=>s.eachRow(r=>r.eachCell(c=>{if(c.value===null)c.value=l.missing;})));
 return Buffer.from(await w.xlsx.writeBuffer());
}
module.exports={daily,workbook};
