'use strict';
const {Twin,DEFAULT,scenario}=DigitalTwin;
const $=id=>document.getElementById(id), names=['Кузов / подготовка','Финальная сборка','Контроль качества'], labels={processing:'Обработка',blocked:'Блокировка: выходной буфер полон',starved:'Нет входящего изделия / спрос исчерпан',materials:'Нет полного комплекта BOM',operator:'Ожидание оператора',offshift:'Вне смены',repair:'Ремонт'};
const clock=t=>[Math.floor(t/3600),Math.floor(t/60)%60,t%60].map(x=>String(x).padStart(2,'0')).join(':');
let model,baseline,timer=null;
function pause(){clearInterval(timer);timer=null;$('play').textContent='▶ Запустить';}
function reset(){pause();const seed=Number($('seed').value);if(!Number.isSafeInteger(seed)||seed<0||seed>4294967295){$('error').textContent='Seed должен быть целым числом от 0 до 4294967295.';return false;}$('error').textContent='';const c=JSON.parse(JSON.stringify(DEFAULT));c.seed=seed;baseline=new Twin(c);model=new Twin(scenario(c,$('scenario').value));render();return true;}
function move(seconds){if($('error').textContent)return;const t=Math.min(model.c.horizon,model.t+seconds);model.advance(t);baseline.advance(t);if(t===model.c.horizon)pause();render();}
function render(){const s=model.snapshot(),b=baseline.snapshot();$('clock').textContent=clock(s.t);$('shift').textContent=`${model.onShift()?'Смена активна':'Вне смены'} · операторов ${model.c.operators} · горизонт 08:00:00`;
 const wip=s.started-s.scrapped-s.produced;
 $('kpis').innerHTML=[['Готово всего',s.produced,'включая отгруженные'],['Отгружено',s.shipped,'из 28 по заказам'],['На складе готовых',s.finished,'ожидают часовой рейс'],['В производстве',wip,'станции + буферы'],['Брак / переделки',`${s.scrapped} / ${s.reworked}`,'не более одной переделки']].map(([a,v,d])=>`<div class="kpi"><small>${a}</small><strong>${v}</strong><span>${d}</span></div>`).join('');
 $('line').innerHTML=s.stations.map((st,i)=>`${i?`<div class="buffer">БУФЕР ${i}<b>${s.buffers[i-1].length} / ${model.c.bufferCaps[i-1]}</b>→</div>`:''}<div class="station ${st.state}"><small>СТАНЦИЯ 0${i+1}</small><h3>${names[i]}</h3><div class="status">${labels[st.state]}</div><div class="job">${st.job?'#'+st.job.id:'—'} ${st.job?.attempt?'↻':''}</div><progress max="${st.cycle}" value="${st.job?st.cycle-st.remaining:0}"></progress><div class="detail">Осталось ${st.remaining} с · цикл ${st.cycle} с<br>Работа ${Math.round(st.time.processing/60)} мин · блокировка ${Math.round(st.time.blocked/60)} мин</div></div>`).join('');
 $('comparison').innerHTML='<table><tr><th>Показатель</th><th>Исходный</th><th>Сценарий</th><th>Δ</th></tr>'+[['Готово','produced'],['Отгружено','shipped'],['Брак','scrapped']].map(([n,k])=>`<tr><td>${n}</td><td>${b[k]}</td><td>${s[k]}</td><td>${s[k]-b[k]>0?'+':''}${s[k]-b[k]}</td></tr>`).join('')+'</table>';
 const losses=s.stations.flatMap((st,i)=>['blocked','materials','operator','repair','starved'].map(k=>({i,k,t:st.time[k]}))).sort((a,b)=>b.t-a.t);const top=losses[0];const busy=s.stations.reduce((a,v)=>v.time.processing>a.time.processing?v:a,s.stations[0]);
 $('cause').textContent=s.t===0?'После запуска здесь появится объяснение по фактически накопленным состояниям станций.':`Максимальная загрузка: ${names[busy.i]} (${Math.round(busy.time.processing/60)} мин обработки). Самое длительное ограничение: ${names[top.i]} — ${labels[top.k].toLowerCase()} (${Math.round(top.t/60)} мин). ${top.k==='operator'?'Двух операторов недостаточно для одновременной работы трёх станций.':top.k==='blocked'?'Следующая операция не успевает освобождать ограниченный буфер.':top.k==='materials'?'Запуск ждёт полный комплект деталей; изменение поставки может сократить простой.':top.k==='repair'?'Оставшаяся обработка возобновится после ремонта и при наличии смены и оператора.':'Проверьте подачу с предыдущей станции и остаток спроса.'} Это диагностика данного прогона, а не доказательство единственной причины.`;
 $('inventory').innerHTML='<table><tr><th>Компонент</th><th>Остаток</th><th>Получено</th><th>Списано</th></tr>'+Object.entries(s.stock).map(([k,v])=>`<tr><td>${{body:'Кузова',engine:'Двигатели',wheels:'Колёса'}[k]}</td><td>${v}</td><td>${s.received[k]}</td><td>${s.started*model.c.bom[k]}</td></tr>`).join('')+'</table>';
 $('orders').innerHTML='<table><tr><th>Заказ / срок</th><th>Отгружено</th><th>Статус</th></tr>'+s.orders.map(o=>`<tr><td>${o.id} / ${clock(o.due)}</td><td>${o.shipped} / ${o.qty}</td><td>${o.completedAt!==null?(o.completedAt<=o.due?'В срок':'С опозданием'):s.t>=o.due?'Просрочен':'В работе'}</td></tr>`).join('')+'</table>';
 $('event-count').textContent=`${s.log.length} событий · последние 100`;$('events').innerHTML=s.log.slice(-100).reverse().map(e=>`<div class="event"><time>${clock(e.at)}</time><span class="tag">${e.type}</span><span>${e.message}</span></div>`).join('');
 const points=data=>data.map(p=>`${10+p.at/model.c.horizon*580},${110-p.shipped/28*100}`).join(' ');$('chart').innerHTML=`<div class="chart-label">Отгружено за 8 часов · <span style="color:#6fcbd4">исходный</span> / <span style="color:#c8f275">сценарий</span></div><svg viewBox="0 0 600 125" role="img" aria-label="График накопленных отгрузок"><path d="M10 10V110H590" fill="none" stroke="#385063"/><polyline points="${points(b.timeline)}" fill="none" stroke="#6fcbd4" stroke-width="4"/><polyline points="${points(s.timeline)}" fill="none" stroke="#c8f275" stroke-width="2"/></svg>`;
}
$('play').onclick=()=>{if(timer){pause();return;}if($('error').textContent)return;if(model.t>=model.c.horizon&&!reset())return;$('play').textContent='Ⅱ Пауза';timer=setInterval(()=>move(120),150);};$('step').onclick=()=>{pause();move(900);};$('finish').onclick=()=>{pause();move(model.c.horizon-model.t);};$('reset').onclick=reset;$('scenario').onchange=reset;$('seed').onchange=reset;reset();

// Compare order service explicitly: throughput alone hides the operator scenario benefit.
const originalRender=render;
render=function(){originalRender();const a=model.orders.filter(o=>o.completedAt!==null&&o.completedAt<=o.due).length,b=baseline.orders.filter(o=>o.completedAt!==null&&o.completedAt<=o.due).length;const row=document.createElement('tr');row.innerHTML=`<td>Заказов закрыто в срок</td><td>${b}</td><td>${a}</td><td>${a-b>0?'+':''}${a-b}</td>`;$('comparison').querySelector('tbody').appendChild(row);if(model.t>0){$('cause').textContent+=` Связь потока: сборка имеет самый длинный базовый цикл (600 с против 360 и 420); кузов заблокирован ${Math.round(model.stations[0].time.blocked/60)} мин, контроль ждёт вход ${Math.round(model.stations[2].time.starved/60)} мин. Переделки дополнительно занимают контроль.`;}const pts=data=>data.flatMap((p,i)=>{const x=10+p.at/model.c.horizon*580;return i?[`${x},${110-data[i-1].shipped/28*100}`,`${x},${110-p.shipped/28*100}`]:[`${x},110`];}).join(' ');const lines=$('chart').querySelectorAll('polyline');lines[0].setAttribute('points',pts(baseline.timeline));lines[1].setAttribute('points',pts(model.timeline));};
reset();
