"use strict";
const {spawn}=require('node:child_process'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const server=spawn(process.execPath,['src/server/main.cjs'],{cwd:path.join(__dirname,'..'),env:{...process.env,PORT:'3121',DB_PATH:path.join(__dirname,'../artifacts/decision-'+Date.now()+'.sqlite')},windowsHide:true,stdio:['ignore','pipe','pipe']});let browser;
try{await new Promise((r,j)=>{server.stdout.once('data',r);server.once('error',j);server.once('exit',c=>j(Error('server '+c)));});
 assert.equal((await fetch('http://127.0.0.1:3121/api/decisions',{method:'POST',headers:{Origin:'http://127.0.0.1:3121','Content-Type':'application/json'},body:'{}'})).status,401);
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3121');await page.locator('#auth-switch').click();await page.locator('#auth-name').fill('Decision Tester');await page.locator('#auth-email').fill('decision@example.test');await page.locator('#auth-password').fill('decision-password-2026');await page.locator('#auth-submit').click();await page.locator('.decision-kpis').waitFor();
 assert.equal(await page.locator('nav a').count(),4);assert.deepEqual(await page.locator('nav a').allTextContents(),['Производство','Сценарии','Риски и рекомендации','Статистика']);assert.equal(await page.locator('.demo').count(),0);assert.equal(await page.locator('nav #logout').count(),0);assert.equal(await page.locator('nav a[href="#settings"]').count(),0);assert.equal(await page.locator('#notice').textContent(),'');assert.equal(await page.locator('main h1').textContent(),'Статистика');assert.equal(await page.locator('#settings-link').isVisible(),true);assert.ok(await page.locator('.brand-logo').evaluate(e=>e.getBoundingClientRect().width>=160));
 await page.locator('#theme-toggle').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'light');await page.reload();await page.locator('.decision-kpis').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'light');assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(244, 243, 239)');await page.locator('#theme-toggle').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');assert.equal(await page.locator('.decision-kpis .stat').count(),5);const tops=await page.locator('.decision-kpis strong').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().top));assert.ok(Math.max(...tops)-Math.min(...tops)<=1,'KPI values share a baseline');const bottoms=await page.locator('#stats-filter input,#stats-filter button').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().bottom));assert.ok(Math.max(...bottoms)-Math.min(...bottoms)<=1,'Dates and actions align');assert.equal(await page.locator('.decision-flow .decision-station').count(),4);assert.ok(!(await page.locator('main').innerText()).includes('Brier'));
 await page.locator('nav a[href="#scenarios"]').click();await page.locator('#template').selectOption('delay');await page.waitForFunction(()=>!document.querySelector('#template').disabled);await page.locator('nav a[href="#overview"]').click();await page.locator('[data-find]').first().click();await page.locator('#recommendations').waitFor();assert.ok(await page.locator('[data-decision-compare]').count()<=3);await page.locator('[data-decision-compare]').first().click();await page.locator('#decision-comparison').waitFor();assert.equal(await page.locator('#decision-comparison tbody tr').count(),5);
 assert.equal(await page.evaluate(()=>config.deliveries[0].at),14400);
 await page.locator('nav a[href="#risks"]').click();await page.locator('#risk-list').waitFor();assert.ok(await page.locator('.cause-chain').count()>0);assert.equal(await page.locator('details.expert-tools').getAttribute('open'),null);
 for(const locale of ['ru','kk','en']){await page.locator('#language').selectOption(locale);await page.waitForFunction(l=>document.documentElement.lang===l,locale);for(const section of ['overview','production','scenarios','risks','settings']){await page.locator(section==='settings'?'#settings-link':`nav a[href="#${section}"]`).click();await page.waitForFunction(k=>location.hash==='#'+k,section);assert.ok(!(await page.locator('main').innerText()).includes('undefined'));}}
 for(const theme of ['light','dark']){if(await page.evaluate(()=>document.documentElement.dataset.theme)!==theme)await page.locator('#theme-toggle').click();for(const width of [1920,1366,390]){await page.setViewportSize({width,height:width===390?844:width===1366?768:1080});for(const section of ['overview','production','scenarios','risks','settings']){await page.locator(section==='settings'?'#settings-link':`nav a[href="#${section}"]`).click();await page.waitForFunction(k=>location.hash==='#'+k,section);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),section+' '+width);}await page.locator('nav a[href="#overview"]').click();await page.screenshot({path:'artifacts/decision-dashboard-'+theme+'-'+width+'.png',fullPage:true});}}
 for(const route of ['line','resources','profile','analytics','caseData','simulation']){await page.evaluate(h=>location.hash=h,route);await page.waitForFunction(k=>location.hash==='#'+k,route);assert.ok(await page.locator('main h1').count()>0);}
 await page.evaluate(()=>location.hash='overview');await page.locator('#stats-filter').waitFor();await page.locator('#stats-from').fill('2026-10-01');await page.locator('#stats-to').fill('2026-10-01');await page.locator('#stats-show').click();assert.equal(await page.locator('.decision-kpis strong').first().textContent(),'122');await page.locator('#stats-from').fill('2026-10-02');await page.locator('#stats-to').fill('2026-10-02');const downloaded=page.waitForEvent('download');await page.locator('#stats-excel').click();const download=await downloaded;assert.ok(download.suggestedFilename().endsWith('.xlsx'));await download.saveAs('artifacts/statistics-report.xlsx');const workbook=new(require('exceljs').Workbook)();await workbook.xlsx.readFile('artifacts/statistics-report.xlsx');assert.equal(workbook.worksheets[1].getCell('C2').value,119);assert.ok(download.suggestedFilename().includes('2026-10-02'));assert.equal(await page.locator('.decision-kpis strong').first().textContent(),'119');await page.screenshot({path:'artifacts/statistics-filtered.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS decision UI: four sections + settings gear, persistent light/dark themes, calculated main risk, what-if, comparison, no automatic change, expert folds, legacy routes, 3 languages, 1920/1366/mobile');
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
