'use strict';
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
 const server=spawn(process.execPath,['src/server/main.cjs'],{cwd:path.join(__dirname,'..'),env:{...process.env,PORT:'3118',DB_PATH:path.join(__dirname,'../artifacts/lab-'+Date.now()+'.sqlite')},windowsHide:true,stdio:['ignore','pipe','pipe']});let browser;
 try {
 await new Promise((r,j)=>{server.stdout.once('data',r);server.once('error',j);server.once('exit',c=>j(Error('server '+c)));});
 assert.equal((await fetch('http://127.0.0.1:3118/api/analytics',{method:'POST',headers:{'Content-Type':'application/json',Origin:'http://127.0.0.1:3118'},body:'{}'})).status,401);
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3118');await page.locator('#auth-switch').click();await page.locator('#auth-name').fill('Lab Tester');await page.locator('#auth-email').fill('lab@example.test');await page.locator('#auth-password').fill('lab-test-password-2026');await page.locator('#auth-submit').click();await page.locator('nav').waitFor();
 await page.evaluate(h=>location.hash=h,'#analytics'); const editPlan=async value=>{const d=page.locator('details').filter({has:page.locator('#plan-json')});if(await d.getAttribute('open')===null)await d.locator('summary').click();await page.locator('#plan-json').fill(value);};await page.locator('#baseline-capture').click();
 await page.locator('#orders-import').setInputFiles({name:'orders.csv',mimeType:'text/csv',buffer:Buffer.from('id,qty,due\n"LAB-1",10,14400\nLAB-2,18,28800\n')});
 await page.waitForFunction(()=>document.querySelector('#plan-json').value.includes('LAB-1')&&!document.querySelector('#plan-apply').disabled);
 await page.locator('[data-plan-path="operators"]').fill('1');await page.locator('#plan-apply').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('#plan-json').value).operators===1&&!document.querySelector('#plan-apply').disabled);let plan=JSON.parse(await page.locator('#plan-json').inputValue());assert.equal(plan.orders.length,2);
 plan.operators=3;await editPlan(JSON.stringify(plan));await page.locator('#plan-apply').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('#plan-json').value).operators===3&&!document.querySelector('#plan-apply').disabled);
 await page.locator('#diagnose').click();await page.waitForFunction(()=>document.querySelector('main').textContent.includes('Выполнение плана:'));
 await page.locator('#mc-n').fill('20');await page.locator('#mc-f').fill('30');await page.locator('#cost-margin').fill('50000');await page.locator('#forecast').click();await page.locator('#report-export').waitFor();
 assert.equal(await page.locator('#cost-margin').inputValue(),'50000');assert.equal(await page.locator('#mc-f').inputValue(),'30');
 const rows=['date,cycle,operators,delay,demand,late',...Array.from({length:100},(_,i)=>[new Date(Date.UTC(2026,0,i+1)).toISOString(),i%2?1000:100,2,0,28,i%2].join(','))].join('\n');
 await page.locator('details').filter({has:page.locator('#history-import')}).last().evaluate(e=>e.open=true);await page.locator('#history-import').setInputFiles({name:'history.csv',mimeType:'text/csv',buffer:Buffer.from(rows)});await page.waitForFunction(()=>document.querySelector('main').textContent.includes('Модель улучшила'));
 const fleet=JSON.parse(await page.locator('#plan-json').inputValue());await page.locator('#fleet-json').fill(JSON.stringify([{name:'Line 1',config:fleet},{name:'Line 2',config:fleet}]));await page.locator('#fleet-run').click();await page.waitForFunction(()=>document.querySelector('main').textContent.includes('Всего готово'));await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/analytics-desktop.png',fullPage:true});await page.screenshot({path:'artifacts/analytics-desktop-top.png'});
 await page.locator('details').filter({has:page.locator('#history-import')}).last().evaluate(e=>e.open=true);const modelText=await page.locator('main').innerText();assert.ok(modelText.includes('Brier'));assert.ok(!modelText.includes('undefined'));
 for(const language of ['en','kk','ru']){await page.locator('#language').selectOption(language);await page.waitForFunction(l=>document.documentElement.lang===l,language);assert.ok(!(await page.locator('main').innerText()).includes('undefined'));}
 await page.evaluate(h=>location.hash=h,'#simulation');await page.locator('[data-calc="end"]').click();await page.waitForFunction(()=>document.querySelector('.clock').textContent.includes('08:00:00'));await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/line-overview.png'});await page.evaluate(h=>location.hash=h,'#analytics');await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/analytics-mobile.png',fullPage:true});await page.screenshot({path:'artifacts/analytics-mobile-top.png'});
 const before=JSON.parse(await page.locator('#plan-json').inputValue());await editPlan('{}');await page.locator('#plan-apply').click();await page.waitForFunction(()=>document.querySelector('#lab-status').textContent.includes('Проверьте'));assert.deepEqual(JSON.parse(await page.locator('#plan-json').inputValue()),before);
 assert.deepEqual(errors,[]);console.log('PASS analytics UI: authenticated API, CSV import, complete plan save, baseline, diagnosis, Monte Carlo, costs, ML holdout, 3 locales, mobile, rejected invalid data');
 }finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
