'use strict';
window.Statistics=(()=>{
 let mode='current',from='',to='',error='';
 const labels={ru:{current:'Текущая смена',days:'По дням',from:'С',to:'По',apply:'Показать',export:'Экспорт в Excel',date:'Дата',plan:'План сборки',actual:'Выпуск',completion:'Выполнение плана',stops:'Простой оборудования, мин',quality:'Качество',empty:'За выбранные дни данных нет',invalid:'Проверьте период: дата начала должна быть не позже даты окончания.',failed:'Не удалось скачать отчёт'},en:{current:'Current shift',days:'By day',from:'From',to:'To',apply:'Show',export:'Export to Excel',date:'Date',plan:'Assembly plan',actual:'Output',completion:'Plan completion',stops:'Equipment downtime, min',quality:'Quality',empty:'No data for the selected days',invalid:'The start date must not be later than the end date.',failed:'Unable to download the report'},kk:{current:'Ағымдағы ауысым',days:'Күндер бойынша',from:'Бастап',to:'Дейін',apply:'Көрсету',export:'Excel экспорты',date:'Күні',plan:'Құрастыру жоспары',actual:'Өнім',completion:'Жоспар орындалуы',stops:'Жабдық тоқтауы, мин',quality:'Сапа',empty:'Таңдалған күндерде деректер жоқ',invalid:'Басталу күні аяқталу күнінен кеш болмауы керек.',failed:'Есеп жүктелмеді'}};
 const tr=(l,k)=>labels[l][k],percent=n=>n===null?'—':(n*100).toFixed(1)+'%',number=n=>Number(n).toLocaleString('ru-RU',{maximumFractionDigits:1});
 function render(ctx){const {lang:l,esc}=ctx,s=k=>tr(l,k),d=Factory.getDataset(),dates=d.performance.map(r=>r.date).sort();if(!from)from=dates[0];if(!to)to=dates.at(-1);
 const toolbar=`<div class="stats-toolbar"><div class="toolbar"><button data-stats-mode="current" class="${mode==='current'?'primary':''}">${s('current')}</button><button data-stats-mode="days" class="${mode==='days'?'primary':''}">${s('days')}</button></div></div><form id="stats-filter"><label class="field">${s('from')}<input id="stats-from" type="date" value="${from}" required></label><label class="field">${s('to')}<input id="stats-to" type="date" value="${to}" required></label><button id="stats-show" class="primary" type="submit">${s('apply')}</button><button id="stats-excel" type="button">${s('export')}</button></form>${error?`<p role="alert">${esc(error)}</p>`:''}`;
 if(mode==='current')return Decision.render(ctx,'overview').replace(/(<h1>.*?<\/h1>)/,'$1'+toolbar);
 const o=FactoryDomain.overview(d,from,to),allDates=[...new Set([...o.rows,...o.stops,...d.quality.filter(r=>r.date>=from&&r.date<=to)].map(r=>r.date))].sort();
 return `<h1>${Decision.tr(l,'dashboard')}</h1>${toolbar}<div class="stats decision-kpis">${[[s('actual'),o.completed],[s('plan'),o.plan],[s('completion'),percent(o.completion)],[s('stops'),number(o.stops.reduce((n,r)=>n+r.minutes,0))],[s('quality'),o.quality?percent(1-o.quality.defectRate):'—']].map(([k,v])=>`<div class="stat"><span>${k}</span><strong>${v}</strong></div>`).join('')}</div><section class="panel">${allDates.length?`<div class="table-wrap"><table><thead><tr>${['date','plan','actual','completion','stops'].map(k=>`<th>${s(k)}</th>`).join('')}</tr></thead><tbody>${allDates.map(date=>{const x=FactoryDomain.overview(d,date,date);return `<tr><td>${date.split('-').reverse().join('.')}</td><td>${x.plan}</td><td>${x.completed}</td><td>${percent(x.completion)}</td><td>${number(x.stops.reduce((n,r)=>n+r.minutes,0))}</td></tr>`;}).join('')}</tbody></table></div>`:`<p>${s('empty')}</p>`}</section>`;
 }
 function bind({config,lang,csrf,action,render}){
 document.querySelectorAll('[data-stats-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.statsMode;error='';render();});
 const form=document.getElementById('stats-filter'),readPeriod=()=>{if(!form.reportValidity())return false;const a=document.getElementById('stats-from').value,b=document.getElementById('stats-to').value;if(a>b){error=tr(lang,'invalid');render();return false;}from=a;to=b;mode='days';error='';return true;};
 if(form)form.onsubmit=e=>{e.preventDefault();if(readPeriod())render();};
 const button=document.getElementById('stats-excel');if(button)button.onclick=()=>{if(!readPeriod())return;action(async()=>{render();const r=await fetch('/api/statistics/export',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({mode:'days',from,to,language:lang})});if(!r.ok){error=tr(lang,'failed');render();return;}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`ALLUR-${from}-${to}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};
 }
 return {isCurrent(){return mode==='current';},render,bind,reset(){mode='current';from='';to='';error='';}};
})();
