'use strict';
window.Statistics=(()=>{
 let mode='demo',from='',to='',error='';
 const labels={ru:{current:'Текущая смена',days:'По дням',from:'С',to:'По',apply:'Показать',export:'Экспорт в Excel',date:'Дата',plan:'План сборки',actual:'Выпуск',completion:'Выполнение плана',stops:'Простой оборудования, мин',quality:'Качество',empty:'За выбранные дни данных нет',invalid:'Проверьте период: дата начала должна быть не позже даты окончания.',failed:'Не удалось скачать отчёт'},en:{current:'Current shift',days:'By day',from:'From',to:'To',apply:'Show',export:'Export to Excel',date:'Date',plan:'Assembly plan',actual:'Output',completion:'Plan completion',stops:'Equipment downtime, min',quality:'Quality',empty:'No data for the selected days',invalid:'The start date must not be later than the end date.',failed:'Unable to download the report'},kk:{current:'Ағымдағы ауысым',days:'Күндер бойынша',from:'Бастап',to:'Дейін',apply:'Көрсету',export:'Excel экспорты',date:'Күні',plan:'Құрастыру жоспары',actual:'Өнім',completion:'Жоспар орындалуы',stops:'Жабдық тоқтауы, мин',quality:'Сапа',empty:'Таңдалған күндерде деректер жоқ',invalid:'Басталу күні аяқталу күнінен кеш болмауы керек.',failed:'Есеп жүктелмеді'}};

 const demoText={ru:{demo:'Демо',note:'Демонстрационные данные за 7 дней. Не являются показателями завода.',trend:'Динамика выпуска',demoExport:'Скачать демо CSV'},en:{demo:'Demo',note:'Seven days of synthetic demo data. Not factory measurements.',trend:'Output trend',demoExport:'Download demo CSV'},kk:{demo:'Демо',note:'7 күндік демонстрациялық деректер. Зауыттың нақты көрсеткіштері емес.',trend:'Өнім динамикасы',demoExport:'Демо CSV жүктеу'}};
 function demoDataset(){const d=structuredClone(Factory.getDataset());d.source={name:'ALLUR — синтетические демоданные',kind:'import',complete:true,pagesReceived:[],totalPages:null};d.performance=[];d.downtimes=[];d.quality=[];d.allocations=[];const output=[116,119,121,117,124,126,128],stops=[54,43,32,61,28,22,18];for(let i=0;i<7;i++){const date='2026-10-'+String(i+1).padStart(2,'0');['Сварка','Окраска','Сборка'].forEach((section,j)=>d.performance.push({date,line:section+'-1',section,plan:130,actual:output[i]+(2-j)*2,workHours:7.4+i*.06,loadPct:90+i+(j===2?1:0)}));d.downtimes.push({date,section:'Сборка',equipment:'Конвейер-01',reason:i===3?'Настройка оборудования':'Обслуживание',minutes:stops[i]});d.quality.push({date,model:d.productionPlan[0].model,inspected:output[i],defective:[3,2,2,3,2,1,1][i]});}return d;}
 const tr=(l,k)=>labels[l][k],percent=n=>n===null?'—':(n*100).toFixed(1)+'%',number=n=>Number(n).toLocaleString('ru-RU',{maximumFractionDigits:1});
 function render(ctx){const {lang:l,esc}=ctx,s=k=>tr(l,k),d=mode==='demo'?demoDataset():Factory.getDataset(),dates=d.performance.map(r=>r.date).sort();if(!from)from=dates[0];if(!to)to=dates.at(-1);
 const toolbar=`<div class="stats-toolbar"><div class="toolbar"><button data-stats-mode="demo" class="${mode==='demo'?'primary':''}">${demoText[l].demo}</button><button data-stats-mode="current" class="${mode==='current'?'primary':''}">${s('current')}</button><button data-stats-mode="days" class="${mode==='days'?'primary':''}">${s('days')}</button></div></div><form id="stats-filter"><label class="field">${s('from')}<input id="stats-from" type="date" value="${from}" required></label><label class="field">${s('to')}<input id="stats-to" type="date" value="${to}" required></label><button id="stats-show" class="primary" type="submit">${s('apply')}</button><button id="stats-excel" type="button">${mode==='demo'?demoText[l].demoExport:s('export')}</button></form>${mode==='demo'?'<p class="demo-stat-note">'+demoText[l].note+'</p>':''}${error?`<p role="alert">${esc(error)}</p>`:''}`;
 if(mode==='current')return Decision.render(ctx,'overview').replace(/(<h1>.*?<\/h1>)/,'$1'+toolbar);
 const o=FactoryDomain.overview(d,from,to),allDates=[...new Set([...o.rows,...o.stops,...d.quality.filter(r=>r.date>=from&&r.date<=to)].map(r=>r.date))].sort();
 return `<h1>${Decision.tr(l,'dashboard')}</h1>${toolbar}<div class="stats decision-kpis">${[[s('actual'),o.completed],[s('plan'),o.plan],[s('completion'),percent(o.completion)],[s('stops'),number(o.stops.reduce((n,r)=>n+r.minutes,0))],[s('quality'),o.quality?percent(1-o.quality.defectRate):'—']].map(([k,v])=>`<div class="stat"><span>${k}</span><strong>${v}</strong></div>`).join('')}</div>${mode==='demo'&&allDates.length?'<section class="panel"><h2>'+demoText[l].trend+'</h2><div class="demo-output-chart">'+allDates.map(date=>{const x=FactoryDomain.overview(d,date,date);return '<div class="demo-output-day"><strong>'+x.completed+'</strong><div class="demo-output-bar" style="height:'+Math.round(x.completed/130*115)+'px"></div><span>'+date.slice(8)+'.10</span></div>';}).join('')+'</div></section>':''}<section class="panel">${allDates.length?`<div class="table-wrap"><table><thead><tr>${['date','plan','actual','completion','stops'].map(k=>`<th>${s(k)}</th>`).join('')}</tr></thead><tbody>${allDates.map(date=>{const x=FactoryDomain.overview(d,date,date);return `<tr><td>${date.split('-').reverse().join('.')}</td><td>${x.plan}</td><td>${x.completed}</td><td>${percent(x.completion)}</td><td>${number(x.stops.reduce((n,r)=>n+r.minutes,0))}</td></tr>`;}).join('')}</tbody></table></div>`:`<p>${s('empty')}</p>`}</section>`;
 }
 function bind({config,lang,csrf,action,render}){
 document.querySelectorAll('[data-stats-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.statsMode;from='';to='';error='';render();});
 const form=document.getElementById('stats-filter'),readPeriod=()=>{if(!form.reportValidity())return false;const a=document.getElementById('stats-from').value,b=document.getElementById('stats-to').value;if(a>b){error=tr(lang,'invalid');render();return false;}from=a;to=b;if(mode!=='demo')mode='days';error='';return true;};
 if(form)form.onsubmit=e=>{e.preventDefault();if(readPeriod())render();};
 const button=document.getElementById('stats-excel');if(button)button.onclick=()=>{if(!readPeriod())return;if(mode==='demo'){const d=demoDataset(),o=FactoryDomain.overview(d,from,to),dates=[...new Set(o.rows.map(r=>r.date))].sort();const rows=[['DEMO / synthetic data'],['Date','Plan','Output','Completion','Equipment downtime (min)'],...dates.map(date=>{const x=FactoryDomain.overview(d,date,date);return [date,x.plan,x.completed,(x.completion*100).toFixed(1)+'%',x.stops.reduce((n,r)=>n+r.minutes,0)];})];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ALLUR-DEMO-'+from+'-'+to+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);render();return;}action(async()=>{render();const r=await fetch('/api/statistics/export',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({mode:'days',from,to,language:lang})});if(!r.ok){error=tr(lang,'failed');render();return;}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`ALLUR-${from}-${to}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};
 }
 return {isCurrent(){return mode==='current';},render,bind,reset(){mode='demo';from='';to='';error='';}};
})();
